from pathlib import Path

PATH=Path('baseball-game.html')
text=PATH.read_text(encoding='utf-8')
MARK='FULL_SIM_V3'
if MARK in text:
    print('FULL_SIM_V3 already applied')
    raise SystemExit(0)

css=r'''
/* FULL_SIM_V3 */
.advanced-card{border-color:#47605d;background:linear-gradient(180deg,#123536,#0b2728)}
.advanced-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.advanced-grid label{font-size:11px;color:#abc0bb;display:grid;gap:5px}.advanced-grid select,.advanced-grid input{width:100%;border:1px solid #3b5c5c;background:#071f20;color:white;border-radius:11px;padding:9px 10px}
.defense-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:9px}.defense-row{background:#0b2425;border:1px solid #315051;border-radius:12px;padding:8px}.defense-row strong{font-size:12px;display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.defense-row select{margin-top:5px;width:100%;background:#173d3d;color:white;border:0;border-radius:8px;padding:6px;font-size:11px}
.pitcher-note{font-size:11px;color:#bdd0cb;margin-top:7px}.ability-pills{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}.ability-pills span{font-size:10px;border:1px solid #385655;background:#112e2f;border-radius:999px;padding:3px 6px}
#managerBtn{background:#203d56;color:white}.controls.v3-controls{grid-template-columns:.55fr .72fr 1.28fr}
.trackman{position:absolute;left:50%;top:8px;transform:translateX(-50%);z-index:25;max-width:72%;background:rgba(3,13,17,.78);border:1px solid rgba(255,255,255,.16);border-radius:999px;padding:6px 10px;font-size:10px;font-weight:850;color:#d9e6e4;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;backdrop-filter:blur(6px)}
.pitcherTag{position:absolute;left:9px;bottom:9px;z-index:24;background:rgba(3,15,18,.76);border:1px solid rgba(255,255,255,.14);border-radius:9px;padding:6px 8px;font-size:10px;color:#cbd8d6}.pitcherTag b{color:#ffe06f}
.manager-grid{display:grid;gap:10px}.manager-section{border:1px solid #315152;border-radius:14px;padding:11px;background:#0b2324}.manager-section h3{margin:0 0 7px;font-size:15px}.manager-section select,.manager-section button{width:100%;border:0;border-radius:10px;padding:10px;background:#173d3d;color:white;font-weight:800}.manager-section button{margin-top:7px;background:#e9b93f;color:#3b2a00}.manager-section button:disabled{opacity:.4}
.game-meta{font-size:11px;color:#b9cbc7;line-height:1.5}.game-meta b{color:#fff}.sound-toggle{display:flex!important;align-items:center;gap:8px!important;grid-template-columns:auto 1fr!important}.sound-toggle input{width:auto!important}
.park-dome{background:linear-gradient(#596a75 0 31%,#9babb2 32%,#345843 34%,#203f2d 100%)!important}.park-taichung{background:linear-gradient(#69bee9 0 33%,#bce6f6 34%,#63886c 35%,#224630 100%)!important}.park-taoyuan{background:linear-gradient(#73b9df 0 33%,#d9e8ef 34%,#6a8d68 35%,#24472e 100%)!important}.park-tainan{background:linear-gradient(#84c8e7 0 33%,#f1dfb8 34%,#6f9064 35%,#28462d 100%)!important}.park-tianmu{background:linear-gradient(#6db8dc 0 33%,#d7e4ea 34%,#64856d 35%,#23442e 100%)!important}.park-chengcing{background:linear-gradient(#7ec6e9 0 33%,#d6edf6 34%,#668b6d 35%,#244831 100%)!important}
.run-strategy{position:absolute;right:9px;bottom:9px;z-index:24;background:rgba(3,15,18,.76);border:1px solid rgba(255,255,255,.14);border-radius:9px;padding:6px 8px;font-size:10px;color:#cbd8d6}
@media(max-width:620px){.advanced-grid{grid-template-columns:1fr}.defense-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.trackman{max-width:62%;top:45px}.pitcherTag{bottom:5px}.run-strategy{display:none}}
'''

js=r'''
// FULL_SIM_V3
const V3_POSITIONS=['C','1B','2B','3B','SS','LF','CF','RF','DH'];
const V3_PARKS={dome:{name:'台北大巨蛋',hr:.94,run:.96,wall:121,cls:'park-dome'},taichung:{name:'洲際棒球場',hr:1,run:1,wall:119,cls:'park-taichung'},taoyuan:{name:'樂天桃園棒球場',hr:1.04,run:1.03,wall:117,cls:'park-taoyuan'},tainan:{name:'台南棒球場',hr:1.07,run:1.05,wall:115,cls:'park-tainan'},tianmu:{name:'天母棒球場',hr:1.02,run:1.01,wall:117,cls:'park-tianmu'},chengcing:{name:'澄清湖棒球場',hr:.98,run:.99,wall:120,cls:'park-chengcing'}};
let v3Pitching={},v3Pitchers=[],v3Starter=null,v3UserPitcher=null,v3OppPitcher=null,v3UserFatigue=0,v3OppFatigue=0,v3Positions={},v3ParkKey=localStorage.getItem('cpblParkV3')||'dome',v3RunStrategy=localStorage.getItem('cpblRunStrategyV3')||'balanced',v3Sound=localStorage.getItem('cpblSoundV3')!=='0',v3LastPhysics=null,v3SwingT=.89,v3UsedSubs=new Set(),v3UsedPitchers=new Set(),v3OriginalLineup=[],v3GameStats={},v3Audio=null,v3ManagerResume=false;
const V3_baseLoadPlayers=loadPlayers,V3_baseRenderLineup=renderLineup,V3_baseUpdateBoard=updateBoard,V3_baseStartGame=startGame,V3_baseReturnToSetup=returnToSetup,V3_baseEndGame=endGame;
function v3Hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return((h>>>0)%10000)/10000}
function v3Ability(p){const s=p?.stats||{},pa=Math.max(0,num(s.PA)||0),w=clamp(pa/120,0,1),avg=.255+((num(s.AVG)??.255)-.255)*w,obp=.325+((num(s.OBP)??.325)-.325)*w,slg=.385+((num(s.SLG)??.385)-.385)*w,sb=num(s.SB)||0,k=num(s.K)||0,bb=num(s.BB)||0,h=v3Hash(p?.name||'player');return{contact:clamp(50+(avg-.255)*250,30,95),power:clamp(48+(slg-.385)*120,28,98),discipline:clamp(50+(obp-avg-.07)*220+(bb-k*.18)*.15,28,94),speed:clamp(48+sb*1.9+(h-.5)*24,32,96)}}
function v3Defense(p,pos){const a=v3Ability(p),h=v3Hash((p?.name||'')+pos);let v=55+(h-.5)*22;if(['SS','2B','CF'].includes(pos))v+=(a.speed-50)*.34;if(['LF','RF','3B'].includes(pos))v+=(a.speed-50)*.16;if(pos==='C')v+=(h-.5)*10;if(pos==='1B')v+=5;return clamp(v,35,95)}
function v3PitchRating(p){const s=p?.pstats||p||{},era=num(s.ERA)??4.2,whip=num(s.WHIP)??1.35,k9=num(s.K9)??7.2,bb9=num(s.BB9)??3.3,gs=num(s.GS)??0,ip=parseFloat(s.IP)||0,h=v3Hash(s.player||p?.name||'pitcher');const overall=clamp(88-era*5.4-(whip-1.1)*18+(k9-7)*2-(bb9-3)*2,40,96);return{overall,control:clamp(78-(bb9-2.5)*8,38,96),stuff:clamp(62+(k9-6)*5+(h-.5)*8,42,98),stamina:clamp(52+gs*1.2+Math.min(30,ip*.12),48,96)}}
function v3PitcherKey(p){return(p?.team||p?.teamName||'')+'|'+(p?.player||p?.name||'')}
function v3BuildFallbackPitchers(){return players.filter(p=>(num(p.stats?.PA)||0)<5).map(p=>{const h=v3Hash(playerId(p));return{team:p.teamName,player:p.name,ERA:2.9+h*2.7,WHIP:1.05+h*.48,K9:5.6+h*5.2,BB9:1.9+h*3.1,GS:Math.round(h*20),G:10+Math.round(h*35),IP:(25+h*95).toFixed(1),synthetic:true}})}
async function v3LoadPitching(){try{const r=await fetch('data/cpbl_pitching_2026.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const j=await r.json();v3Pitching=j.players||{};v3Pitchers=Object.values(v3Pitching);if(v3Pitchers.length<40)throw Error('too few pitchers')}catch(e){console.warn('pitching data fallback',e);v3Pitchers=v3BuildFallbackPitchers();v3Pitching=Object.fromEntries(v3Pitchers.map(p=>[v3PitcherKey(p),p]))}}
function v3PitcherObj(raw){if(!raw)return null;const teamName=raw.team||raw.teamName,name=raw.player||raw.name;return{name,teamName,pstats:raw,teamKey:teamByName[teamName]||''}}
function v3BestPitcher(teamKey,starter=true,exclude=new Set()){let a=v3Pitchers.filter(x=>teamByName[x.team]===teamKey&&!exclude.has(v3PitcherKey(x)));a=a.filter(x=>starter?(num(x.GS)||0)>=2:true);if(!a.length)a=v3Pitchers.filter(x=>teamByName[x.team]===teamKey&&!exclude.has(v3PitcherKey(x)));a.sort((x,y)=>{const xr=v3PitchRating(x),yr=v3PitchRating(y);return yr.overall-xr.overall+(starter?((num(y.GS)||0)-(num(x.GS)||0))*.35:((num(y.G)||0)-(num(x.G)||0))*.08)});return v3PitcherObj(a[0])}
function v3AllPitcherOptions(teamKey=null,exclude=new Set()){return v3Pitchers.filter(x=>(!teamKey||teamByName[x.team]===teamKey)&&!exclude.has(v3PitcherKey(x))).sort((a,b)=>v3PitchRating(b).overall-v3PitchRating(a).overall)}
function v3EnsurePositions(){if(lineup.length!==9)return;const alive=new Set(lineup.map(playerId));for(const k of Object.keys(v3Positions))if(!alive.has(k))delete v3Positions[k];const used=new Set(Object.values(v3Positions));lineup.forEach((p,i)=>{const id=playerId(p);if(!v3Positions[id]){const pos=V3_POSITIONS.find(x=>!used.has(x))||V3_POSITIONS[i];v3Positions[id]=pos;used.add(pos)}});localStorage.setItem('cpblDefenseV3',JSON.stringify(v3Positions))}
function v3RenderDefense(){const box=$('v3Defense');if(!box)return;if(lineup.length!==9){box.innerHTML='<div class="sub">選滿 9 人後即可指定守備位置。</div>';return}v3EnsurePositions();box.innerHTML='<div class="defense-grid">'+lineup.map(p=>{const id=playerId(p),pos=v3Positions[id],d=Math.round(v3Defense(p,pos));return`<div class="defense-row"><strong>${p.name}</strong><select data-v3pos="${id}">${V3_POSITIONS.map(x=>`<option ${x===pos?'selected':''}>${x}</option>`).join('')}</select><div class="ability-pills"><span>守 ${d}</span><span>速 ${Math.round(v3Ability(p).speed)}</span></div></div>`}).join('')+'</div>';qsa('[data-v3pos]').forEach(s=>s.onchange=()=>{const id=s.dataset.v3pos,next=s.value,old=v3Positions[id],other=Object.keys(v3Positions).find(k=>k!==id&&v3Positions[k]===next);v3Positions[id]=next;if(other)v3Positions[other]=old;localStorage.setItem('cpblDefenseV3',JSON.stringify(v3Positions));v3RenderDefense()})}
function v3SetupUI(){if($('v3Advanced'))return;try{v3Positions=JSON.parse(localStorage.getItem('cpblDefenseV3')||'{}')}catch(e){v3Positions={}}const lineupCard=$('lineup')?.closest('.card');if(lineupCard){const d=document.createElement('div');d.id='v3Defense';d.style.marginTop='12px';lineupCard.appendChild(d)}const oppCard=$('opponentSelect')?.closest('.card')||$('startGameBtn')?.closest('.card');const card=document.createElement('section');card.id='v3Advanced';card.className='card advanced-card';card.innerHTML=`<h2>進階比賽設定</h2><div class="advanced-grid"><label>先發投手<select id="v3Starter"></select></label><label>比賽球場<select id="v3Park">${Object.entries(V3_PARKS).map(([k,p])=>`<option value="${k}" ${k===v3ParkKey?'selected':''}>${p.name}</option>`).join('')}</select></label><label>跑壘策略<select id="v3Run"><option value="safe">保守</option><option value="balanced">平衡</option><option value="aggressive">積極</option></select></label><label class="sound-toggle"><input id="v3Sound" type="checkbox" ${v3Sound?'checked':''}><span>比賽音效</span></label></div><div id="v3PitcherInfo" class="pitcher-note">讀取投手資料中…</div>`;if(oppCard)oppCard.parentNode.insertBefore(card,oppCard);else document.querySelector('#setupApp .screen').appendChild(card);$('v3Run').value=v3RunStrategy;$('v3Park').onchange=e=>{v3ParkKey=e.target.value;localStorage.setItem('cpblParkV3',v3ParkKey)};$('v3Run').onchange=e=>{v3RunStrategy=e.target.value;localStorage.setItem('cpblRunStrategyV3',v3RunStrategy)};$('v3Sound').onchange=e=>{v3Sound=e.target.checked;localStorage.setItem('cpblSoundV3',v3Sound?'1':'0')};v3PopulateStarter();v3RenderDefense();v3InjectGameUI()}
function v3PopulateStarter(){const s=$('v3Starter');if(!s)return;const arr=v3AllPitcherOptions();s.innerHTML=arr.slice(0,180).map(p=>{const r=v3PitchRating(p);return`<option value="${v3PitcherKey(p)}">${p.team}｜${p.player}　ERA ${num(p.ERA)!=null?Number(p.ERA).toFixed(2):'—'}　OVR ${Math.round(r.overall)}</option>`}).join('');const saved=localStorage.getItem('cpblStarterV3');if(saved&&[...s.options].some(o=>o.value===saved))s.value=saved;v3SelectStarter(s.value);s.onchange=()=>{localStorage.setItem('cpblStarterV3',s.value);v3SelectStarter(s.value)}}
function v3SelectStarter(key){const raw=v3Pitchers.find(p=>v3PitcherKey(p)===key)||v3Pitchers[0];v3Starter=v3PitcherObj(raw);const info=$('v3PitcherInfo');if(info&&v3Starter){const r=v3PitchRating(v3Starter);info.textContent=`${v3Starter.name}｜控球 ${Math.round(r.control)}・球威 ${Math.round(r.stuff)}・耐力 ${Math.round(r.stamina)}${raw?.synthetic?'（暫用遊戲估算，官方投手資料更新後會自動替換）':''}`}}
function v3InjectGameUI(){const controls=document.querySelector('.controls');if(controls&&!$('managerBtn')){controls.classList.add('v3-controls');const b=document.createElement('button');b.id='managerBtn';b.className='control';b.textContent='管理';controls.insertBefore(b,$('swingBtn'));b.onclick=v3OpenManager}const scene=$('scene');if(scene&&!$('v3Track')){const t=document.createElement('div');t.id='v3Track';t.className='trackman';t.textContent='Statcast：等待比賽開始';scene.appendChild(t);const p=document.createElement('div');p.id='v3PitcherTag';p.className='pitcherTag';scene.appendChild(p);const r=document.createElement('div');r.id='v3RunTag';r.className='run-strategy';scene.appendChild(r)}if(!$('v3ManagerOverlay')){const o=document.createElement('div');o.id='v3ManagerOverlay';o.className='overlay hidden';o.innerHTML=`<div class="modal"><h2>比賽管理</h2><div id="v3ManagerBody" class="manager-grid"></div><div class="modal-actions"><button id="v3ManagerClose" class="primary">回到比賽</button><button id="v3ManagerMenu" class="secondary">結束比賽</button></div></div>`;document.body.appendChild(o);$('v3ManagerClose').onclick=v3CloseManager;$('v3ManagerMenu').onclick=()=>{v3CloseManager(false);if(confirm('要結束這場比賽嗎？'))returnToSetup()}}}
function v3Bench(){const ids=new Set(lineup.map(playerId));return players.filter(p=>!ids.has(playerId(p))).sort((a,b)=>(num(b.stats?.OPS)||0)-(num(a.stats?.OPS)||0))}
function v3OpenManager(){if(!playing)return;$('v3ManagerOverlay').classList.remove('hidden');v3ManagerResume=true;clearMotion();const body=$('v3ManagerBody'),bench=v3Bench().slice(0,120),pitchers=v3AllPitcherOptions(null,v3UsedPitchers).slice(0,120),runnerOpts=bases.map((r,i)=>r?`<option value="${i}">${i+1}壘｜${r.name}</option>`:'').join('');body.innerHTML=`<div class="manager-section"><h3>換投</h3><div class="game-meta">目前：<b>${v3UserPitcher?.name||'—'}</b>　疲勞 ${Math.round(v3UserFatigue)}%</div><select id="v3Relief">${pitchers.map(p=>`<option value="${v3PitcherKey(p)}">${p.team}｜${p.player}　ERA ${num(p.ERA)!=null?Number(p.ERA).toFixed(2):'—'}</option>`).join('')}</select><button id="v3DoRelief">換上投手</button></div><div class="manager-section"><h3>代打</h3><div class="game-meta">目前打者：<b>${currentPlayer()?.name||'—'}</b></div><select id="v3PH">${bench.map(p=>`<option value="${playerId(p)}">${p.teamName}｜${p.name}　OPS ${rate(p.stats?.OPS)}</option>`).join('')}</select><button id="v3DoPH">換代打</button></div><div class="manager-section"><h3>代跑</h3><select id="v3Base">${runnerOpts||'<option value="">目前壘上沒有人</option>'}</select><select id="v3PR">${bench.map(p=>`<option value="${playerId(p)}">${p.teamName}｜${p.name}　速度 ${Math.round(v3Ability(p).speed)}</option>`).join('')}</select><button id="v3DoPR" ${runnerOpts?'':'disabled'}>換代跑</button></div>`;$('v3DoRelief').onclick=()=>{const raw=v3Pitchers.find(p=>v3PitcherKey(p)===$('v3Relief').value);if(raw){v3UserPitcher=v3PitcherObj(raw);v3UsedPitchers.add(v3PitcherKey(raw));v3UserFatigue=0;setMsg('換投完成',v3UserPitcher.name+' 登板','');v3RenderGameMeta();v3OpenManager()}};$('v3DoPH').onclick=()=>{const p=players.find(x=>playerId(x)===$('v3PH').value);if(!p)return;const idx=batIndex%9,old=lineup[idx],pos=v3Positions[playerId(old)];lineup[idx]=p;delete v3Positions[playerId(old)];v3Positions[playerId(p)]=pos;v3UsedSubs.add(playerId(p));setMsg('代打',p.name+' 上場','');v3RenderGameMeta();v3CloseManager(true)};$('v3DoPR').onclick=()=>{const bi=Number($('v3Base').value),p=players.find(x=>playerId(x)===$('v3PR').value);if(!Number.isInteger(bi)||!p||!bases[bi])return;const old=bases[bi],idx=lineup.findIndex(x=>playerId(x)===playerId(old));if(idx>=0){const pos=v3Positions[playerId(lineup[idx])];delete v3Positions[playerId(lineup[idx])];lineup[idx]=p;v3Positions[playerId(p)]=pos}bases[bi]=p;v3UsedSubs.add(playerId(p));setMsg('代跑',p.name+' 上場','');updateBoard();v3CloseManager(true)}}
function v3CloseManager(resume=true){$('v3ManagerOverlay')?.classList.add('hidden');if(resume&&playing&&v3ManagerResume){v3ManagerResume=false;schedulePitch(500)}}
function v3RenderGameMeta(){const tag=$('v3PitcherTag'),run=$('v3RunTag');if(tag){const r=v3PitchRating(v3UserPitcher);tag.innerHTML=`我方投手 <b>${v3UserPitcher?.name||'—'}</b>｜OVR ${Math.round(r.overall)}｜疲勞 ${Math.round(v3UserFatigue)}%`}if(run)run.textContent='跑壘：'+({safe:'保守',balanced:'平衡',aggressive:'積極'}[v3RunStrategy]||'平衡')}
function v3AudioReady(){if(!v3Sound)return null;try{if(!v3Audio)v3Audio=new(window.AudioContext||window.webkitAudioContext)();if(v3Audio.state==='suspended')v3Audio.resume();return v3Audio}catch(e){return null}}
function v3Beep(kind){const c=v3AudioReady();if(!c)return;const o=c.createOscillator(),g=c.createGain(),now=c.currentTime;let f=kind==='hit'?170:kind==='hr'?115:kind==='catch'?260:kind==='strike'?420:300,d=kind==='hr'?.35:.08;o.frequency.setValueAtTime(f,now);if(kind==='hit')o.frequency.exponentialRampToValueAtTime(85,now+.07);if(kind==='hr')o.frequency.exponentialRampToValueAtTime(60,now+.3);g.gain.setValueAtTime(kind==='hr'?.15:.08,now);g.gain.exponentialRampToValueAtTime(.001,now+d);o.connect(g).connect(c.destination);o.start(now);o.stop(now+d)}
function v3Park(){return V3_PARKS[v3ParkKey]||V3_PARKS.dome}
function v3OppDefense(){return 61+v3Hash(opponent)*23}
function v3TeamDefense(){if(lineup.length!==9)return 65;return lineup.reduce((sum,p)=>sum+v3Defense(p,v3Positions[playerId(p)]||'DH'),0)/9}
function v3Poisson(lambda){let L=Math.exp(-lambda),k=0,p=1;do{k++;p*=Math.random()}while(p>L&&k<7);return Math.max(0,k-1)}
function v3PitchTypes(p){const r=v3PitchRating(p),h=v3Hash(p?.name||'pitcher'),fast=Math.round(142+(r.stuff-60)*.16);return[{n:'四縫線',s:[fast-3,fast+3],d:[760,920],c:6,drop:3},{n:h>.5?'滑球':'卡特球',s:[fast-15,fast-9],d:[880,1050],c:30,drop:11},{n:h>.25?'變速球':'指叉球',s:[fast-23,fast-15],d:[980,1180],c:11,drop:24},{n:h>.7?'曲球':'伸卡球',s:[fast-29,fast-18],d:[1020,1240],c:22,drop:34}]}
loadPlayers=async function(){await V3_baseLoadPlayers();await v3LoadPitching();v3SetupUI();v3RenderDefense()};
renderLineup=function(){V3_baseRenderLineup();v3EnsurePositions();v3RenderDefense();if($('startGameBtn')&&lineup.length===9&&!v3Starter)v3PopulateStarter()};
updateBoard=function(){V3_baseUpdateBoard();v3RenderGameMeta();const cur=currentPlayer(),gs=v3GameStats[playerId(cur)]||{AB:0,H:0,HR:0};if($('batterRealStats')&&cur)$('batterRealStats').textContent=`AVG ${rate(cur.stats?.AVG)}・SLG ${rate(cur.stats?.SLG)}・OPS ${rate(cur.stats?.OPS)}｜本場 ${gs.H}-${gs.AB}${gs.HR?'・HR '+gs.HR:''}`};
startGame=function(){if(!v3Starter){alert('請先選擇先發投手');return}v3OriginalLineup=lineup.slice();v3UserPitcher=v3Starter;v3UsedPitchers=new Set([v3PitcherKey(v3Starter)]);v3UsedSubs=new Set();v3UserFatigue=0;v3OppFatigue=0;v3GameStats={};v3OppPitcher=v3BestPitcher(opponent,true,new Set());const scene=$('scene');if(scene){scene.classList.remove(...Object.values(V3_PARKS).map(p=>p.cls));scene.classList.add(v3Park().cls)}v3AudioReady();V3_baseStartGame();bases=[null,null,null];updateBoard();const tr=$('v3Track');if(tr)tr.textContent=`${v3Park().name}｜對手先發 ${v3OppPitcher?.name||'—'}`};
returnToSetup=function(){lineup=v3OriginalLineup.length?v3OriginalLineup.slice():lineup;V3_baseReturnToSetup();v3RenderDefense()};$('backSetupBtn').onclick=returnToSetup;$('menuBtn').onclick=()=>{if(confirm('要結束這場比賽並回選人畫面嗎？'))returnToSetup()};
simulateCpu=function(first=false){const pr=v3PitchRating(v3UserPitcher),def=v3TeamDefense(),park=v3Park(),fat=Math.max(0,v3UserFatigue-pr.stamina*.75),off=teamOffenseStrength(opponent);let lambda=.43+off*.24+(park.run-1)*1.8-(pr.overall-70)*.008-(def-65)*.004+fat*.006;lambda=clamp(lambda,.10,1.18);const runs=v3Poisson(lambda);cpuScore+=runs;v3UserFatigue=clamp(v3UserFatigue+11+rand(0,8),0,100);updateBoard();if(inning===9&&userScore>cpuScore)return endGame('比賽勝利！');setMsg(inning+'局下',`${teams[opponent].short} 本局 ${runs} 分・${v3UserPitcher?.name||''} 疲勞 ${Math.round(v3UserFatigue)}%`,'');if(inning>=7&&v3OppFatigue>72){const next=v3BestPitcher(opponent,false,new Set([v3PitcherKey(v3OppPitcher)]));if(next){v3OppPitcher=next;v3OppFatigue=0}}showIntro();schedulePitch(first?1000:1100)};
throwPitch=function(){if(!playing)return;$('pitcher').classList.remove('windup');$('pitcher').classList.add('release');const rr=v3PitchRating(v3OppPitcher),types=v3PitchTypes(v3OppPitcher),p=types[Math.floor(Math.random()*types.length)];lastPitch=p.n;lastSpeed=Math.round(rand(...p.s));pitchDuration=rand(...p.d)*(1-(rr.stuff-65)*.0025);const zoneProb=clamp(.59+rr.control*.0018,.63,.79),inZone=Math.random()<zoneProb;if(inZone){const spread=clamp(.46-(rr.control-50)*.0026,.22,.47);pitchTargetX=clamp(.5+rand(-spread,spread),.04,.96);pitchTargetY=clamp(.5+rand(-spread,spread),.04,.96)}else{const side=Math.floor(Math.random()*4);if(side===0){pitchTargetX=rand(-.22,-.04);pitchTargetY=rand(.05,.95)}if(side===1){pitchTargetX=rand(1.04,1.22);pitchTargetY=rand(.05,.95)}if(side===2){pitchTargetX=rand(.05,.95);pitchTargetY=rand(-.22,-.04)}if(side===3){pitchTargetX=rand(.05,.95);pitchTargetY=rand(1.04,1.22)}}pitchCurve=(Math.random()<.5?-1:1)*p.c;pitchDrop=p.drop;pitchStart=performance.now();pitching=true;v3OppFatigue=clamp(v3OppFatigue+1.6,0,100);$('pitchInfo').textContent=`${v3OppPitcher?.name||''}｜${lastPitch} ${lastSpeed} km/h`;const tr=$('v3Track');if(tr)tr.textContent=`投球 ${lastPitch} ${lastSpeed} km/h｜投手 ${v3OppPitcher?.name||'—'}`;$('ball').style.display='block';raf=requestAnimationFrame(animatePitch)};
swing=function(){if(!playing||!pitching)return;v3AudioReady();const batter=$('batter'),bat=$('bat');batter.classList.add('swing');bat.classList.add('swing');setTimeout(()=>{batter.classList.remove('swing');bat.classList.remove('swing')},240);const t=clamp((performance.now()-pitchStart)/pitchDuration,0,1);v3SwingT=t;const timingErr=Math.abs(t-.89),aimErr=Math.hypot(aimX-pitchTargetX,aimY-pitchTargetY);pitching=false;if(raf)cancelAnimationFrame(raf);$('ball').style.display='none';if(timingErr>.23||aimErr>.72){strikes++;v3Beep('strike');setMsg('揮空！','時機或準星位置沒對上','bad');if(strikes>=3)return finishPA('K');updateBoard();return schedulePitch(820)}const tq=clamp(1-timingErr/.20,0,1),aq=clamp(1-aimErr/.56,0,1),contact=tq*.58+aq*.42;resolveContact(contact)};
function v3Physics(q){const a=v3Ability(currentPlayer()),pr=v3PitchRating(v3OppPitcher),stuffPenalty=(pr.stuff-65)*.045;let ev=clamp(108+q*70+(a.power-50)*.18-stuffPenalty+rand(-7,7),82,191),angle=clamp(7+q*24+(pitchTargetY-aimY)*30+rand(-13,13),-22,48),spray=clamp((.89-v3SwingT)*155+(aimX-pitchTargetX)*42+rand(-9,9),-48,48);if(Math.abs(spray)>44)return{foul:true,ev,angle,spray,distance:0,hang:0};let distance;if(angle<0)distance=clamp(18+(ev-90)*.48+rand(-8,9),8,78);else if(angle<10)distance=clamp(48+(ev-95)*.64+rand(-8,10),28,112);else distance=clamp(46+(ev-92)*1.02-Math.abs(angle-27)*1.15+rand(-7,8),35,150);const hang=clamp(.7+Math.max(0,angle)*.105+distance*.006,.7,6.2),park=v3Park(),wall=park.wall+(Math.abs(spray)<12?3:-2)+(Math.abs(spray)>32?-3:0),oppDef=v3OppDefense();let result='OUT',label='守備出局';if(angle<3){const hitP=clamp(.13+q*.38+(a.speed-50)*.003-(oppDef-65)*.003,.08,.62);if(Math.random()<hitP){result='1B';label='內野安打'}else label='內野滾地出局'}else if(distance*park.hr>=wall&&angle>=15&&angle<=42){result='HR';label='全壘打'}else{let catchP=clamp(.78-(q-.5)*.40+(oppDef-65)*.006+(hang-3)*.035-(distance-95)*.005,.14,.93);if(angle<12)catchP-=.22;if(Math.random()>catchP){if(distance>105&&Math.abs(spray)>18)result=a.speed>72&&Math.random()<.2?'3B':'2B';else if(distance>88&&Math.random()<.32)result='2B';else result='1B';label=result==='1B'?'安打':result==='2B'?'二壘安打':'三壘安打'}else label=angle>18?'外野飛球接殺':'平飛球接殺'}return{foul:false,ev,angle,spray,distance,hang,result,label,wall}}
resolveContact=function(c){const a=v3Ability(currentPlayer()),pr=v3PitchRating(v3OppPitcher);c=clamp(c+(a.contact-50)*.0011+(a.power-50)*.0007-(pr.stuff-65)*.0009,0,1);const ph=v3Physics(c);v3LastPhysics=ph;if(ph.foul){if(strikes<2)strikes++;setMsg('界外球',`擊球初速 ${Math.round(ph.ev)} km/h`,'');updateBoard();return schedulePitch(820)}v3Beep(ph.result==='HR'?'hr':'hit');const dir=ph.spray<-8?'拉打':ph.spray>8?'推打':'中間方向';const tr=$('v3Track');if(tr)tr.textContent=`擊球初速 ${Math.round(ph.ev)} km/h｜仰角 ${Math.round(ph.angle)}°｜${dir}｜${Math.round(ph.distance)} m`;showHitThen(ph.result,ph.label)};
showHitThen=function(result,label=''){resetHitCamera();const cam=$('hitCam'),ball=$('flyball'),splash=$('resultSplash'),ph=v3LastPhysics||{spray:0,distance:80,angle:15};cam.classList.remove('hidden');const text=result==='HR'?'HOME RUN!':result==='3B'?'三壘安打':result==='2B'?'二壘安打':result==='1B'?'安打':label||'出局';splash.textContent=text;const tx=clamp(50+ph.spray*.72,12,88),ty=result==='HR'?7:clamp(73-ph.distance*.27,38,68),isHr=result==='HR',dur=isHr?1650:1050;cam.classList.toggle('hrMode',isHr);const fielder=nearestHitFielder(tx,ty);if(fielder&&!isHr){const rect=fielder.getBoundingClientRect(),crect=cam.getBoundingClientRect(),sx=(rect.left+rect.width/2-crect.left)/crect.width*100,sy=(rect.top+rect.height/2-crect.top)/crect.height*100;fielder.animate([{left:sx+'%',top:sy+'%'},{left:tx+'%',top:(ty+3)+'%'}],{duration:Math.min(900,420+ph.hang*90),easing:'cubic-bezier(.2,.7,.2,1)',fill:'forwards'})}ball.animate([{left:'50%',top:'78%',transform:'scale(1)'},{left:((tx+50)/2)+'%',top:Math.max(18,(ty+78)/2-15)+'%',transform:'scale(.8)'},{left:tx+'%',top:ty+'%',transform:'scale(.58)'}],{duration:dur,easing:'cubic-bezier(.18,.65,.15,1)',fill:'forwards'});if(result!=='OUT')animateRunner(result,isHr?2050:result==='3B'?1500:result==='2B'?1250:950);if(result==='OUT'&&fielder)setTimeout(()=>{v3Beep('catch');const flash=$('catchFlash');flash.style.left=tx+'%';flash.style.top=ty+'%';flash.style.opacity='1';flash.classList.remove('pop');void flash.offsetWidth;flash.classList.add('pop');splash.textContent=label||'接殺出局'},Math.min(850,dur*.72));if(isHr)setTimeout(()=>splash.textContent=`全壘打！ ${Math.round(ph.distance)}m`,720);setTimeout(()=>{cam.classList.add('hidden');resetHitCamera();finishPA(result,label)},isHr?2150:result==='3B'?1550:result==='2B'?1320:1120)};
function v3RunnerAdvanceChance(runner,extra){const sp=v3Ability(runner).speed,base=v3RunStrategy==='safe'?.18:v3RunStrategy==='aggressive'?.62:.38;return clamp(base+(sp-60)*.007+(extra||0),.08,.88)}
advance=function(type){let runs=0;const old=bases.map(x=>x||null),batter=currentPlayer();if(type==='BB'){const n=[batter,null,null];if(old[0]){n[1]=old[0];if(old[1]){n[2]=old[1];if(old[2])runs++}else n[2]=old[2]}else{n[1]=old[1];n[2]=old[2]}bases=n}if(type==='1B'){const n=[batter,null,null];if(old[2])runs++;if(old[1]){if(Math.random()<v3RunnerAdvanceChance(old[1],.14))runs++;else n[2]=old[1]}if(old[0]){if(Math.random()<v3RunnerAdvanceChance(old[0],-.08))n[2]=old[0];else n[1]=old[0]}bases=n}if(type==='2B'){const n=[null,batter,null];if(old[2])runs++;if(old[1])runs++;if(old[0]){if(Math.random()<v3RunnerAdvanceChance(old[0],.03))runs++;else n[2]=old[0]}bases=n}if(type==='3B'){runs=old.filter(Boolean).length;bases=[null,null,batter]}if(type==='HR'){runs=1+old.filter(Boolean).length;bases=[null,null,null]}return runs};
finishPA=function(result,label=''){const p=currentPlayer(),s=currentStat(),g=v3GameStats[playerId(p)]||(v3GameStats[playerId(p)]={PA:0,AB:0,H:0,HR:0});s.PA++;g.PA++;let runs=0;if(result==='K'){s.AB++;s.K++;g.AB++;outs++;v3Beep('strike');label='三振出局'}else if(result==='BB'){s.BB++;runs=advance('BB');label='四壞保送'}else if(result==='OUT'){s.AB++;g.AB++;outs++}else{s.AB++;s.H++;g.AB++;g.H++;if(result==='2B')s.D2++;if(result==='3B')s.D3++;if(result==='HR'){s.HR++;g.HR++}runs=advance(result);s.RBI+=runs;label=result==='1B'?'安打！':result==='2B'?'二壘安打！':result==='3B'?'三壘安打！':'全壘打！！！'}userScore+=runs;setMsg(label,(runs?runs+' 分打點・':'')+p.name,result==='OUT'||result==='K'?'bad':'good');batIndex=(batIndex+1)%9;balls=strikes=0;saveDb();updateBoard();if(inning===9&&userScore>cpuScore)return endGame('再見勝！');if(outs>=3)return endHalf();showIntro();schedulePitch(1100)};
endGame=function(title){V3_baseEndGame(title);const tr=$('v3Track');if(tr)tr.textContent=`終場｜${v3Park().name}｜${title}`};
'''

if '</style>' not in text:
    raise RuntimeError('style marker not found')
if 'loadPlayers();\n})();' not in text:
    raise RuntimeError('script marker not found')
text=text.replace('</style>',css+'\n</style>',1)
text=text.replace('loadPlayers();\n})();',js+'\nloadPlayers();\n})();',1)
PATH.write_text(text,encoding='utf-8')
print('Applied FULL_SIM_V3')
