from pathlib import Path

p = Path("baseball-game.html")
s = p.read_text(encoding="utf-8")

old_css = '''.hitCam{position:absolute;inset:0;z-index:40;background:linear-gradient(#71bde9 0 27%,#275239 28%);overflow:hidden}.hitCam.hidden{display:none!important}.hitCam .stad{position:absolute;left:-5%;right:-5%;top:18%;height:22%;background:#465b5e;clip-path:polygon(0 30%,15% 7%,50% 0,85% 7%,100% 30%,100% 100%,0 100%)}.hitCam .green{position:absolute;left:0;right:0;top:34%;bottom:0;background:repeating-linear-gradient(90deg,#2f7a45 0 42px,#3a844d 42px 84px)}.hitCam .diamond{position:absolute;left:50%;top:66%;width:min(52vw,360px);height:min(42vw,290px);background:#ac7349;transform:translate(-50%,-50%) rotate(45deg)}.hitCam .diamond:after{content:"";position:absolute;inset:18%;background:#3a7d49}.flyball{position:absolute;width:18px;height:18px;border-radius:50%;background:white;box-shadow:0 0 10px #fff8,0 3px 5px #0006;left:50%;top:74%;z-index:5}.resultSplash{position:absolute;left:50%;top:14%;transform:translateX(-50%);z-index:6;font-size:clamp(28px,8vw,58px);font-weight:1000;text-shadow:0 5px 12px #0009;color:#fff;white-space:nowrap}'''
new_css = '''.hitCam{position:absolute;inset:0;z-index:40;background:linear-gradient(#71bde9 0 27%,#275239 28%);overflow:hidden;transition:filter .25s ease}.hitCam.hidden{display:none!important}.hitCam.hrMode{filter:saturate(1.15) brightness(.88)}.hitCam .stad{position:absolute;left:-5%;right:-5%;top:18%;height:22%;background:#465b5e;clip-path:polygon(0 30%,15% 7%,50% 0,85% 7%,100% 30%,100% 100%,0 100%)}.hitCam .green{position:absolute;left:0;right:0;top:34%;bottom:0;background:repeating-linear-gradient(90deg,#2f7a45 0 42px,#3a844d 42px 84px)}.hitCam .diamond{position:absolute;left:50%;top:66%;width:min(52vw,360px);height:min(42vw,290px);background:#ac7349;transform:translate(-50%,-50%) rotate(45deg)}.hitCam .diamond:after{content:"";position:absolute;inset:18%;background:#3a7d49}.flyball{position:absolute;width:18px;height:18px;border-radius:50%;background:white;box-shadow:0 0 10px #fff8,0 3px 5px #0006;left:50%;top:78%;z-index:9}.resultSplash{position:absolute;left:50%;top:12%;transform:translateX(-50%);z-index:12;font-size:clamp(28px,8vw,58px);font-weight:1000;text-shadow:0 5px 12px #0009;color:#fff;white-space:nowrap}.hitCam.hrMode .resultSplash{color:#ffe56a;text-shadow:0 0 20px #ffb000,0 7px 18px #000}.hitFielder{position:absolute;width:18px;height:30px;z-index:8;transform:translate(-50%,-50%);transition:filter .2s}.hitFielder:before{content:"";position:absolute;left:5px;top:0;width:9px;height:9px;border-radius:50%;background:#bd815e}.hitFielder:after{content:"";position:absolute;left:2px;top:8px;width:14px;height:21px;border-radius:4px;background:linear-gradient(#f4f3ed,#cfd4d2);box-shadow:0 12px 0 -5px #eee}.hf-lf{left:23%;top:48%}.hf-cf{left:50%;top:44%}.hf-rf{left:77%;top:48%}.hf-ss{left:39%;top:62%}.hf-2b{left:61%;top:62%}.hf-1b{left:70%;top:71%}.hf-3b{left:30%;top:71%}.hitRunner{position:absolute;left:50%;top:84%;width:18px;height:28px;z-index:10;transform:translate(-50%,-50%);opacity:0}.hitRunner:before{content:"";position:absolute;left:5px;top:0;width:9px;height:9px;border-radius:50%;background:#b97b59;box-shadow:0 -3px 0 1px #18253b}.hitRunner:after{content:"";position:absolute;left:2px;top:8px;width:14px;height:20px;border-radius:4px;background:#e98b2d}.catchFlash{position:absolute;width:42px;height:42px;border:3px solid #fff;border-radius:50%;z-index:11;opacity:0;transform:translate(-50%,-50%) scale(.5);pointer-events:none}.catchFlash.pop{animation:catchPop .38s ease-out}@keyframes catchPop{0%{opacity:1;transform:translate(-50%,-50%) scale(.35)}100%{opacity:0;transform:translate(-50%,-50%) scale(1.45)}}'''

old_html = '<div id="hitCam" class="hitCam hidden"><div class="stad"></div><div class="green"></div><div class="diamond"></div><div id="resultSplash" class="resultSplash"></div><div id="flyball" class="flyball"></div></div>'
new_html = '<div id="hitCam" class="hitCam hidden"><div class="stad"></div><div class="green"></div><div class="diamond"></div><div class="hitFielder hf-lf" data-hf="lf"></div><div class="hitFielder hf-cf" data-hf="cf"></div><div class="hitFielder hf-rf" data-hf="rf"></div><div class="hitFielder hf-ss" data-hf="ss"></div><div class="hitFielder hf-2b" data-hf="2b"></div><div class="hitFielder hf-1b" data-hf="1b"></div><div class="hitFielder hf-3b" data-hf="3b"></div><div id="hitRunner" class="hitRunner"></div><div id="catchFlash" class="catchFlash"></div><div id="resultSplash" class="resultSplash"></div><div id="flyball" class="flyball"></div></div>'

old_js = '''function showHitThen(result,label=''){const cam=$('hitCam'),ball=$('flyball');cam.classList.remove('hidden');const text=result==='HR'?'HOME RUN!':result==='3B'?'三壘安打':result==='2B'?'二壘安打':result==='1B'?'安打':label||'出局';$('resultSplash').textContent=text;const target={HR:[50,15], '3B':[28,38], '2B':[72,42], '1B':[60,58],OUT:[50,48]}[result]||[50,50];ball.animate([{left:'50%',top:'78%',transform:'scale(1)'},{left:target[0]+'%',top:target[1]+'%',transform:result==='HR'?'scale(.55)':'scale(.7)'}],{duration:760,easing:'cubic-bezier(.2,.7,.2,1)',fill:'forwards'});setTimeout(()=>{cam.classList.add('hidden');ball.getAnimations().forEach(a=>a.cancel());finishPA(result,label)},850)}'''
new_js = '''function resetHitCamera(){const cam=$('hitCam'),ball=$('flyball'),runner=$('hitRunner');cam.classList.remove('hrMode');ball.getAnimations().forEach(a=>a.cancel());runner.getAnimations().forEach(a=>a.cancel());runner.style.opacity='0';runner.style.left='50%';runner.style.top='84%';qsa('[data-hf]').forEach(f=>{f.getAnimations().forEach(a=>a.cancel());f.style.filter='';});const flash=$('catchFlash');flash.classList.remove('pop');flash.style.opacity='0'}
function nearestHitFielder(x,y){const map={lf:[23,48],cf:[50,44],rf:[77,48],ss:[39,62],'2b':[61,62],'1b':[70,71],'3b':[30,71]};let best=null,bd=1e9;for(const [k,[fx,fy]] of Object.entries(map)){const d=(fx-x)**2+(fy-y)**2;if(d<bd){bd=d;best=k}}return qsa('[data-hf]').find(f=>f.dataset.hf===best)}
function animateRunner(result,duration){const runner=$('hitRunner');const pts={'1B':[[50,84],[70,70]],'2B':[[50,84],[70,70],[50,51]],'3B':[[50,84],[70,70],[50,51],[30,70]],HR:[[50,84],[70,70],[50,51],[30,70],[50,84]]}[result];if(!pts)return;runner.style.opacity='1';const frames=pts.map((p,i)=>({left:p[0]+'%',top:p[1]+'%',offset:i/(pts.length-1),transform:`translate(-50%,-50%) ${i%2?'rotate(5deg)':'rotate(-5deg)'}`}));runner.animate(frames,{duration,easing:'linear',fill:'forwards'})}
function showHitThen(result,label=''){resetHitCamera();const cam=$('hitCam'),ball=$('flyball'),splash=$('resultSplash');cam.classList.remove('hidden');const text=result==='HR'?'HOME RUN!':result==='3B'?'三壘安打':result==='2B'?'二壘安打':result==='1B'?'安打':label||'出局';splash.textContent=text;const target={HR:[50,8],'3B':[26,41],'2B':[74,44],'1B':[62,58],OUT:[50,49]}[result]||[50,50];const isHr=result==='HR',dur=isHr?1450:980;cam.classList.toggle('hrMode',isHr);const fielder=nearestHitFielder(target[0],target[1]);if(fielder&&!isHr){const rect=fielder.getBoundingClientRect(),crect=cam.getBoundingClientRect();const sx=(rect.left+rect.width/2-crect.left)/crect.width*100,sy=(rect.top+rect.height/2-crect.top)/crect.height*100;fielder.animate([{left:sx+'%',top:sy+'%'},{left:(target[0]+(result==='OUT'?0:(target[0]>50?-4:4)))+'%',top:(target[1]+4)+'%'}],{duration:760,easing:'cubic-bezier(.2,.7,.2,1)',fill:'forwards'})}const ballFrames=isHr?[{left:'50%',top:'78%',transform:'scale(1)'},{left:'48%',top:'43%',transform:'scale(.78)'},{left:'52%',top:'8%',transform:'scale(.38)'}]:[{left:'50%',top:'78%',transform:'scale(1)'},{left:((target[0]+50)/2)+'%',top:((target[1]+78)/2-10)+'%',transform:'scale(.82)'},{left:target[0]+'%',top:target[1]+'%',transform:'scale(.68)'}];ball.animate(ballFrames,{duration:dur,easing:isHr?'cubic-bezier(.18,.65,.15,1)':'cubic-bezier(.2,.7,.2,1)',fill:'forwards'});if(result!=='OUT')animateRunner(result,isHr?1800:result==='3B'?1450:result==='2B'?1200:950);if(result==='OUT'&&fielder){setTimeout(()=>{const flash=$('catchFlash');flash.style.left=target[0]+'%';flash.style.top=target[1]+'%';flash.style.opacity='1';flash.classList.remove('pop');void flash.offsetWidth;flash.classList.add('pop');splash.textContent=label||'接殺出局'},720)}if(isHr){setTimeout(()=>{splash.textContent='全壘打！'},720)}setTimeout(()=>{cam.classList.add('hidden');resetHitCamera();finishPA(result,label)},isHr?1900:result==='3B'?1500:result==='2B'?1280:1080)}'''

for old, new, label in ((old_css, new_css, "CSS"), (old_html, new_html, "HTML"), (old_js, new_js, "JS")):
    if old not in s:
        if new in s:
            print(f"{label} already patched")
            continue
        raise SystemExit(f"Expected {label} block not found")
    s = s.replace(old, new)

p.write_text(s, encoding="utf-8")
print("Applied baseball realism v2")
